import turtle
trtl = turtle.Turtle()
screen=turtle.Screen()
screen.bgcolor('black')
trtl.pencolor('light blue')
trtl.pensize(4)
trtl.shape('turtle')
trtl.penup()
trtl.setpos(0,-60)
trtl.pendown()
trtl.circle(60)